version: "3.8"

services:
  onyot-ai:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TWO_CAPTCHA_API_KEY=${TWO_CAPTCHA_API_KEY}
      - VPN_USERNAME=${VPN_USERNAME}
      - VPN_PASSWORD=${VPN_PASSWORD}
    command: ["xvfb-run", "python", "Skip_Tracing/truppl_parser.py"]
