version: "3.8"

services:
  onyot-ai:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TWO_CAPTCHA_API_KEY=${TWO_CAPTCHA_API_KEY}
      - VPN_USERNAME=${VPN_USERNAME}
      - VPN_PASSWORD=${VPN_PASSWORD}
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
      - ./Skip Tracing/logfile.log:/app/Skip Tracing/logfile.log
    CMD ["xvfb-run", "python", "Skip Tracing/truppl_parser.py"]

