name: Google Search Extractor

on:
  workflow_dispatch:

jobs:
  run-search:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install googleapis puppeteer-extra puppeteer-extra-plugin-stealth puppeteer

      - name: Create service account key
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > service-account.json

      - name: Run script
        run: node fullAddress.js